[package]
name = "battlesnake"
version = "0.1.0"
authors = ["Maxwell Mazzocchi <maxwell.mazzocchi@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
log = "0.4"
env_logger = "0.8"
json = "0.11"
serde = "1.0.118"
actix-files = "0.5.0"
rand = "0.8.1"
log4rs = "1.0.0"
serde_yaml = "0.8.17"
